default_platform(:android)

platform :android do
  def env_properties(prefix)
    {
      "#{prefix}_API_BASE_URL" => ENV.fetch("#{prefix}_API_BASE_URL"),
      "#{prefix}_COGNITO_CLIENT_ID" => ENV.fetch("#{prefix}_COGNITO_CLIENT_ID"),
      "#{prefix}_S3_BUCKET_NAME" => ENV.fetch("#{prefix}_S3_BUCKET_NAME")
    }
  end

  def dev_properties
    env_properties("DEV")
  end

  def prod_properties
    env_properties("PROD")
  end

  desc "Run Unit Tests (used in CI)"
  lane :test do
    gradle(task: "testDevDebugUnitTest", properties: dev_properties, print_command: false)
  end



  desc "Build the DEV environment APK (used in CD)"
  lane :build_dev do
    gradle(task: "assemble", flavor: "Dev", build_type: "Release", properties: dev_properties, print_command: false)
  end

  desc "Build the PROD environment APK and AAB (used in CD)"
  lane :build_prod do
    gradle(task: "assemble", flavor: "Prod", build_type: "Release", properties: prod_properties, print_command: false)
    gradle(task: "bundle", flavor: "Prod", build_type: "Release", properties: prod_properties, print_command: false)
  end
end