package com.appvoyager.cloudphotos.domain.auth.model

enum class SignInStep {

    CONFIRM_SIGN_IN_WITH_CUSTOM_CHALLENGE,
    CONFIRM_SIGN_IN_WITH_SMS_MFA_CODE,
    CONFIRM_SIGN_IN_WITH_TOTP_CODE,
    CONTINUE_SIGN_IN_WITH_MFA_SELECTION,
    CONTINUE_SIGN_IN_WITH_TOTP_SETUP,
    CONFIRM_SIGN_IN_WITH_NEW_PASSWORD,
    DONE,
    UNKNOWN

}
