name: CI

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - main
      - develop

permissions:
  contents: read

concurrency:
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.1'
          bundler-cache: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Execute Unit Tests (DEV & PROD)
        run: bundle exec fastlane test_all

      - name: Execute Fastlane (build only)
        run: bundle exec fastlane build_dev
